export default {
  preset: '542',
  remembered: {
    542: {
      0: {
        projection: 'poincare',
        p: 5,
        q: 4,
        r: 2,
        layers: 10,
        limit: 1750,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'plain',
        strokeColor: '#414141',
        backgroundColor: '#000000',
        straight: false,
        wedges: false,
        wedgesColor: '#000000',
        wedgesAlpha: 8,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    442: {
      0: {
        projection: 'orthographic',
        p: 4,
        q: 4,
        r: 2,
        layers: 15,
        limit: 2500,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'plain',
        strokeColor: '#414141',
        backgroundColor: '#000000',
        straight: true,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 8,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    632: {
      0: {
        projection: 'orthographic',
        p: 6,
        q: 3,
        r: 2,
        layers: 15,
        limit: 2500,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'plain',
        strokeColor: '#414141',
        backgroundColor: '#000000',
        straight: true,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 8,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    333: {
      0: {
        projection: 'orthographic',
        p: 3,
        q: 3,
        r: 3,
        layers: 15,
        limit: 2500,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'plain',
        strokeColor: '#414141',
        backgroundColor: '#000000',
        straight: true,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 8,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    342: {
      0: {
        projection: 'stereographic',
        p: 5,
        q: 3,
        r: 2,
        layers: 4,
        limit: 1750,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'plain',
        strokeColor: '#414141',
        backgroundColor: '#000000',
        straight: false,
        wedges: true,
        wedgesColor: '#ffffff',
        wedgesAlpha: 30,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    '472 Wedges': {
      0: {
        projection: 'poincare',
        p: 4,
        q: 7,
        r: 2,
        layers: 10,
        limit: 1000,
        coloredShift: 37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'none',
        strokeColor: '#000000',
        backgroundColor: '#000000',
        straight: false,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 8,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    443: {
      0: {
        projection: 'poincare',
        p: 4,
        q: 4,
        r: 3,
        layers: 10,
        limit: 1000,
        coloredShift: 71,
        fill: 'odd',
        fillColor: '#0000dd',
        fillColorEven: '#dd0000',
        stroke: 'plain',
        strokeColor: '#000000',
        backgroundColor: '#000000',
        straight: false,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 20,
        tokenPrecision: 2,
        curvePrecision: 10,
      },
    },
    '662 Straight': {
      0: {
        projection: 'poincare',
        p: 6,
        q: 6,
        r: 2,
        layers: 10,
        limit: 1000,
        coloredShift: -37,
        fill: 'colored',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'none',
        strokeColor: '#ffffff',
        backgroundColor: '#000000',
        straight: true,
        wedges: true,
        wedgesColor: '#000000',
        wedgesAlpha: 10,
        tokenPrecision: 2,
        curvePrecision: 16,
      },
    },
    Triangles: {
      0: {
        projection: 'poincare',
        p: 3,
        q: 7,
        r: 2,
        layers: 20,
        limit: 3000,
        coloredShift: 37,
        fill: 'none',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'colored',
        strokeColor: '#ffffff',
        backgroundColor: '#000000',
        straight: false,
        wedges: false,
        wedgesColor: '#000000',
        wedgesAlpha: 10,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    Inverted: {
      0: {
        projection: 'inverted',
        p: 6,
        q: 4,
        r: 2,
        layers: 20,
        limit: 3000,
        coloredShift: 37,
        fill: 'none',
        fillColor: '#000000',
        fillColorEven: '#000000',
        stroke: 'colored',
        strokeColor: '#ffffff',
        backgroundColor: '#000000',
        straight: false,
        wedges: false,
        wedgesColor: '#000000',
        wedgesAlpha: 10,
        tokenPrecision: 2,
        curvePrecision: 12,
      },
    },
    Football: {
      0: {
        projection: 'klein',
        p: 7,
        q: 3,
        r: 2,
        layers: 10,
        limit: 1000,
        coloredShift: 37,
        fill: 'plain',
        fillColor: '#f7f7f7',
        fillColorEven: '#f7f7f7',
        stroke: 'plain',
        strokeColor: '#595959',
        backgroundColor: '#000000',
        straight: false,
        wedges: false,
        wedgesColor: '#000000',
        wedgesAlpha: 10,
        tokenPrecision: 2,
        curvePrecision: 10,
      },
    },
  },
}
